# simulation.yml
simulation:
  file_path: data/block_0.csv
  start_date: 2012-10-24
  timescale: d
  simulation_speed: 300
  interval_seconds: 6
  log_level: INFO

hardware:
  mock_mode: true  # Only mock_mode is configurable in YAML